### ISSUE TITLE
Clear documentation for handling events

### ISSUE THREAD

**Issue by soerenmartius** [egeloen/IvoryGoogleMapBundle#128]
Hi,

I was trying to add an event to my map. The documentation for binding events is not clear. I think it would be great to provide a clear documentation with some examples.

**Comment by KevinArtus** [comment]
Hi @egeloen, @smartius 
I get the same problem as u get 2 years ago.
I would like to add a event to my google Map.

I build map object like this :
$map = new Map();
$map->setPrefixJavascriptVariable('map_');
        $map->setHtmlContainerId('map_canvas');
        $map->setAsync(false);
        $map->setAutoZoom(true);
        $map->setCenter(-0.3483401, 49.1755575, true);
        $map->setMapOption('zoom', 13);
        $map->setBound(-2.1, -3.9, 2.6, 1.4, true, true);
        $map->setMapOption('mapTypeId', 'roadmap');
        $map->setMapOption('disableDefaultUI', false);
        $map->setMapOption('disableDoubleClickZoom', true);
        $map->setStylesheetOption('width', '1200px');
        $map->setStylesheetOption('height', '700px');
        $map->setLanguage('fr');

And then, i try to add a event to this map :
$event = new Event();
        $event->setInstance($map->getJavascriptVariable());
        $event->setEventName("click");
        $handle = 'function(){alert("/!\ OK CLIQUE OK /!\");}';
        $event->setHandle($handle);
        $event->setCapture(true);
        $map->getEventManager()->addDomEventOnce($event);

The problem is that when i use this line : $map->getEventManager()->addDomEventOnce($event);
and render the map with twig {{ google_map(map) }}, google map disappears.
Do you have find how to add event to the click on map ?
Ty

**Comment by smartius** [comment]
Hi @KevinArtus , 

i end up not using this bundle anymore since it wasn't flexible enough for my purposes.

**Comment by KevinArtus** [comment]
@smartius, than for your response.
Wich bundle do you have use to develop google map with Symfony 2 ?
I need one wich can allow me to display map with marker, road and click on map.
I have to build web project with PHP, so it's not really recommend to use Google Map API V3 directly.
