### ISSUE TITLE
Is this bundle still maintained?

### ISSUE THREAD

**Issue by sdespont** [egeloen/IvoryGoogleMapBundle#150]
Hello,

Your bundle seems very useful, but is it still maintained? Does it still works with last Google Map V3 version?

Thanks

**Comment by nurikabe** [comment]
+1

**Comment by giovkanata** [comment]
:+1:

**Comment by chandon** [comment]
This bundle seems not to be maintained anymore. It throws a lots of deprecation warnings since Symfony 2.7, even more with Symfony 2.8 and doesn't work with symfony 3. I think it's better to use another bundle with Symfony 2.7 and later

**Comment by Platzengys** [comment]
@chandon do you have any suggestions for alternative bundles? Or should I write functionality I need by myself and don't use this bundle anymore?

**Comment by chandon** [comment]
@Platzengys no idea for an alternative bundle, i'm still using this one... 
For google maps, i think it's better to use the api directly and to avoid bundles (i just need some time to do it and to remove IvoryFoofleMapBundle)

**Comment by egeloen** [comment]
I know I'm very late here but it is not the first time I will announce what I will say :)

The bundle is currently not maintained mostly due to the amount of code there is in this bundle/library and the fact I don't use it in any of my current projects... So, not easy to maintain something you have not used since ages...

Anyway, I'm totally open to give the library/bundle to someone which have interest in it and would like to bring the project to the next level. If you're interestting, you can comment here or directly send me a message, email, whatever for discussing it.

**Comment by KevinArtus** [comment]
Bundle worl well with SYmfony 2.8. I do not find depreciated functionnality.

**Comment by fungio** [comment]
I made a fork with 3.0 compatibility.
If you are interested : https://packagist.org/packages/fungio/google-map-bundle
I'll try to maintain it.

**Comment by nurikabe** [comment]
@fungio Why not take over the main fork from @egeloen?

**Comment by fungio** [comment]
I needed this bundle to work with sf3 and I couldn't wait for egeloen to maintain it or to give it to someone so I made my own fork.

**Comment by egeloen** [comment]
The 2.x version of the bundle is not maintained anymore but the upcoming 3.x version will be.
