### ISSUE TITLE
Polylines | escaping?

### ISSUE THREAD

**Issue by aarsla** [egeloen/IvoryGoogleMapBundle#186]
I am receiving encodedPolyline from DirectionRequest and once dumped it has single backslashes:

`...@iCzcDgJl\oHfJgOpc...` and works properly on encoder test: https://developers.google.com/maps/documentation/utilities/polylineutility

However, once the same polyline is appended to a map it ends up with multiple backslashes:

`...@iCzcDgJl\\\\oHfJgOpc...`

in rendered javascript code under "path": google.maps.geometry.encoding.decodePath("...").

[polylines.txt](https://github.com/egeloen/IvoryGoogleMapBundle/files/595032/polylines.txt)

**Comment by egeloen** [comment]
Thanks for reporting this issue. It seems a duplicate of #183 Can you give a try to https://github.com/egeloen/ivory-google-map/pull/196 ?

**Comment by aarsla** [comment]
Just did, its a no-go. :(

**Comment by egeloen** [comment]
@aarsla Basically, there are two ways to fix it and I'm not sure of which one is the best... By default, the library relies on `json_encode` without any bit flag which results to have the default PHP behavior of the json encoding (which is not compatible with rendering an encoded polyline).

First solution: Globally configure the json builder to not escape slashes. Then, all the generated JSON will no longer have escaped slahes.

Second solution: Only configure the json builder to not escape slashes but just for encoded polylines.

Personally, I prefer the second solution since escaping slahes is here on purpose (eg. Avoiding to get an unescaped char in the middle of the JSON which would close the last open HTML tag, See http://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped).

**Comment by egeloen** [comment]
@aarsla Can you give a try to the referenced PR? I just discover there is an `addslashes` in the rendering but can't remember why I added it in the first place...

**Comment by aarsla** [comment]
Works like a charm.

Thanks!
